version: "3.8"
services:
    mongodb:
        image: mongo:4.4
        container_name: mongodb
        restart: always
        ports: 
            - ${MONGO_PORT}:27017
        environment: 
            MONGO_INITDB_USERNAME: ${MONGO_USER}
            MONGO_INITDB_PASSWORD: ${MONGO_PWD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
            - mongodb_data:/data/db
    
    api:
        image: node:latest
        container_name: apinodejs
        restart: always
        ports:
            - ${PORT}:${PORT}
        volumes:
            - .:/app
        working_dir: /app
        depends_on: 
            - mongodb
        links: 
            - mongodb
        command: "npm run dev"

volumes:
  mongodb_data: